데이터 출처 : https://www.data.go.kr/data/15041101/fileData.do

In [2]:
import pandas as pd

In [102]:
# 데이터 불러오기
df1 = pd.read_csv("./국가철도공단_부산_지하철_주소데이터_20211123.csv", encoding="cp949")
df1

    철도운영기관명   선명       역명                 지번주소                 도로명주소
0    부산교통공사  1호선  다대포해수욕장  부산시 사하구 다대동 1552-16  부산광역시 사하구 다대로 지하 692
1    부산교통공사  1호선     다대포항      부산시 사하구 다대동 909  부산광역시 사하구 다대로 지하 548
2    부산교통공사  1호선       낫개    부산시 사하구 다대동 63-13   부산광역시 사하구 다대로 지하422
3    부산교통공사  1호선      신장림      부산시 사하구 장림동 380   부산광역시 사하구 다대로 지하310
4    부산교통공사  1호선       장림    부산시 사하구 장림동 185-9   부산광역시 사하구 다대로 지하230
..      ...  ...      ...                  ...                   ...
119     NaN  NaN      NaN                  NaN                   NaN
120     NaN  NaN      NaN                  NaN                   NaN
121     NaN  NaN      NaN                  NaN                   NaN
122     NaN  NaN      NaN                  NaN                   NaN
123     NaN  NaN      NaN                  NaN                   NaN

[124 rows x 5 columns]

In [103]:
# 결측치 제거
df1 = df1.dropna(axis=0)
df1

    철도운영기관명   선명          역명                      지번주소                   도로명주소
0    부산교통공사  1호선     다대포해수욕장       부산시 사하구 다대동 1552-16    부산광역시 사하구 다대로 지하 692
1    부산교통공사  1호선        다대포항           부산시 사하구 다대동 909    부산광역시 사하구 다대로 지하 548
2    부산교통공사  1호선          낫개         부산시 사하구 다대동 63-13     부산광역시 사하구 다대로 지하422
3    부산교통공사  1호선         신장림           부산시 사하구 장림동 380     부산광역시 사하구 다대로 지하310
4    부산교통공사  1호선          장림         부산시 사하구 장림동 185-9     부산광역시 사하구 다대로 지하230
..      ...  ...         ...                       ...                     ...
109  부산교통공사  4호선          석대     부산광역시 해운대구 석대동 574-14     부산광역시 해운대구 석대천로 121
110  부산교통공사  4호선   영산대(아랫반송)     부산광역시 해운대구 반송동 698-12      부산광역시 해운대구 반송로 803
111  부산교통공사  4호선  동부산대학(윗반송)     부산광역시 해운대구 반송동 385-56      부산광역시 해운대구 반송로 917
112  부산교통공사  4호선          고촌   부산광역시 기장군 철마면 고촌리 518-2   부산광역시 기장군 철마면 반송로 991
113  부산교통공사  4호선  안평(고촌주택단지)  부산광역시 기장군 철마면 안평리 543-23  부산광역시 기장군 철마면 반송로 1001

[114 rows x 5 columns]

In [104]:
#필요한 열만 추출
df1.drop(["철도운영기관명","도로명주소"],axis=1, inplace=True)
df1

C:\Users\admin\AppData\Local\Temp\ipykernel_19224\524813263.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(["철도운영기관명","도로명주소"],axis=1, inplace=True)

      선명          역명                      지번주소
0    1호선     다대포해수욕장       부산시 사하구 다대동 1552-16
1    1호선        다대포항           부산시 사하구 다대동 909
2    1호선          낫개         부산시 사하구 다대동 63-13
3    1호선         신장림           부산시 사하구 장림동 380
4    1호선          장림         부산시 사하구 장림동 185-9
..   ...         ...                       ...
109  4호선          석대     부산광역시 해운대구 석대동 574-14
110  4호선   영산대(아랫반송)     부산광역시 해운대구 반송동 698-12
111  4호선  동부산대학(윗반송)     부산광역시 해운대구 반송동 385-56
112  4호선          고촌   부산광역시 기장군 철마면 고촌리 518-2
113  4호선  안평(고촌주택단지)  부산광역시 기장군 철마면 안평리 543-23

[114 rows x 3 columns]

In [105]:
# 동, 리만 추출
df1["행정동"] = df1["지번주소"].str.split().str[2:3].astype("str")
df1

C:\Users\admin\AppData\Local\Temp\ipykernel_19224\2651736454.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["행정동"] = df1["지번주소"].str.split().str[2:3].astype("str")

      선명          역명                      지번주소      행정동
0    1호선     다대포해수욕장       부산시 사하구 다대동 1552-16  ['다대동']
1    1호선        다대포항           부산시 사하구 다대동 909  ['다대동']
2    1호선          낫개         부산시 사하구 다대동 63-13  ['다대동']
3    1호선         신장림           부산시 사하구 장림동 380  ['장림동']
4    1호선          장림         부산시 사하구 장림동 185-9  ['장림동']
..   ...         ...                       ...      ...
109  4호선          석대     부산광역시 해운대구 석대동 574-14  ['석대동']
110  4호선   영산대(아랫반송)     부산광역시 해운대구 반송동 698-12  ['반송동']
111  4호선  동부산대학(윗반송)     부산광역시 해운대구 반송동 385-56  ['반송동']
112  4호선          고촌   부산광역시 기장군 철마면 고촌리 518-2  ['철마면']
113  4호선  안평(고촌주택단지)  부산광역시 기장군 철마면 안평리 543-23  ['철마면']

[114 rows x 4 columns]

In [106]:
df1["행정동"] = df1["행정동"].str.split("[").str.get(-1).str.replace("]","")
df1["행정동"] = df1["행정동"].str.split("'").str.get(1)

C:\Users\admin\AppData\Local\Temp\ipykernel_19224\2827570717.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df1["행정동"] = df1["행정동"].str.split("[").str.get(-1).str.replace("]","")
C:\Users\admin\AppData\Local\Temp\ipykernel_19224\2827570717.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["행정동"] = df1["행정동"].str.split("[").str.get(-1).str.replace("]","")

In [115]:
df1

      선명          역명                      지번주소  행정동
0    1호선     다대포해수욕장       부산시 사하구 다대동 1552-16  다대동
1    1호선        다대포항           부산시 사하구 다대동 909  다대동
2    1호선          낫개         부산시 사하구 다대동 63-13  다대동
3    1호선         신장림           부산시 사하구 장림동 380  장림동
4    1호선          장림         부산시 사하구 장림동 185-9  장림동
..   ...         ...                       ...  ...
109  4호선          석대     부산광역시 해운대구 석대동 574-14  석대동
110  4호선   영산대(아랫반송)     부산광역시 해운대구 반송동 698-12  반송동
111  4호선  동부산대학(윗반송)     부산광역시 해운대구 반송동 385-56  반송동
112  4호선          고촌   부산광역시 기장군 철마면 고촌리 518-2  철마면
113  4호선  안평(고촌주택단지)  부산광역시 기장군 철마면 안평리 543-23  철마면

[114 rows x 4 columns]

In [125]:
# 기장군은 면,리
df1.loc[112, "행정동"] = "철마면 고촌리"
df1.loc[113, "행정동"] = "철마면 안평리"

df1.loc[12, "행정동"] = "서대신동"
df1.loc[13, "행정동"] = "동대신동"
df1.loc[14, "행정동"] = "토성동"
df1.loc[15, "행정동"] = "남포동"
df1.loc[16, "행정동"] = "남포동"
df1.loc[17,"행정동"] = "중앙동"

In [129]:
df1.head(50)

     선명                역명                   지번주소   행정동
0   1호선           다대포해수욕장    부산시 사하구 다대동 1552-16   다대동
1   1호선              다대포항        부산시 사하구 다대동 909   다대동
2   1호선                낫개      부산시 사하구 다대동 63-13   다대동
3   1호선               신장림        부산시 사하구 장림동 380   장림동
4   1호선                장림      부산시 사하구 장림동 185-9   장림동
5   1호선                동매      부산시 사하구 신평동 544-2   신평동
6   1호선                신평      부산광역시 사하구 신평동 646   신평동
7   1호선         하단(부산본병원)      부산광역시 사하구 하단동 491   하단동
8   1호선          당리(사하구청)      부산광역시 사하구 당리동 323   당리동
9   1호선                사하      부산광역시 사하구 괴정동 661   괴정동
10  1호선                괴정    부산광역시 사하구 괴정동 934-3   괴정동
11  1호선          대티(동주대학)    부산광역시 사하구 괴정동 317-1   괴정동
12  1호선               서대신    부산광역시 서구 서대신동2가 338  서대신동
13  1호선               동대신  부산광역시 서구 동대신동2가 428-9  동대신동
14  1호선                토성    부산광역시 서구 토성동3가 11-3   토성동
15  1호선               자갈치   부산광역시 중구 남포동6가 117-1   남포동
16  1호선                남포      부산광역시 중구 남포동1가 11   남포동
17  1호선                중앙    부산광역시 중구 중앙동4가 26-3   중앙동
18  1호선                부산    부산광역시 동구 초량동 1206-1   초량동
19  1호선                초량      부산광역시 동구 초량동 1170   초량동
20  1호선               부산진      부산광역시 동구 초량동 1170   초량동
21  1호선                좌천       부산광역시 동구 좌천동 236   좌천동
22  1호선                범일       부산광역시 동구 범일동 949   범일동
23  1호선               범내골   부산광역시 부산진구 범천동 948-4   범천동
24  1호선                서면   부산광역시 부산진구 부전동 573-1   부전동
25  1호선  부전(부산시민공원·송상현광장)   부산광역시 부산진구 부전동 573-1   부전동
26  1호선                양정     부산광역시 부산진구 양정동 408   양정동
27  1호선            시청(연제)   부산광역시 연제구 연산동 1328-9   연산동
28  1호선                연산   부산광역시 연제구 연산동 1515-1   연산동
29  1호선                교대    부산광역시 연제구 거제동 72-25   거제동
30  1호선                동래      부산광역시 동래구 온천동 527   온천동
31  1호선                명륜    부산광역시 동래구 온천동 489-4   온천동
32  1호선               온천장   부산광역시 동래구 온천동 1750-1   온천동
33  1호선               부산대      부산광역시 금정구 장전동 427   장전동
34  1호선      장전(부산가톨릭대학교)      부산광역시 금정구 장전동 242   장전동
35  1호선                구서      부산광역시 금정구 구서동 475   구서동
36  1호선                두실      부산광역시 금정구 구서동 262   구서동
37  1호선       남산(부산외국대학교)    부산광역시 금정구 남산동 136-1   남산동
38  1호선               범어사       부산광역시 금정구 청룡동 47   청룡동
39  1호선       노포(종합버스터미널)      부산광역시 금정구 노포동 133   노포동
40  2호선        장산(해운대백병원)     부산광역시 해운대구 좌동 1491    좌동
41  2호선                중동   부산광역시 해운대구 중동 1783-1    중동
42  2호선               해운대      부산광역시 해운대구 우동 656    우동
43  2호선                동백    부산광역시 해운대구 우동 991-3    우동
44  2호선        벡스코(시립미술관)   부산광역시 해운대구 우동 1086-3    우동
45  2호선   센텀시티(BEXCO·신세계)     부산광역시 해운대구 우동 1524    우동
46  2호선                민락    부산광역시 수영구 민락동 345-1   민락동
47  2호선                수영   부산광역시 수영구 광안동 1091-1   광안동
48  2호선                광안      부산광역시 수영구 광안동 205   광안동
49  2호선               금련산       부산광역시 수영구 남천동 78   남천동

In [130]:
df1.drop(["지번주소"],axis=1, inplace=True)
df1

C:\Users\admin\AppData\Local\Temp\ipykernel_19224\2004770994.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.drop(["지번주소"],axis=1, inplace=True)

      선명          역명      행정동
0    1호선     다대포해수욕장      다대동
1    1호선        다대포항      다대동
2    1호선          낫개      다대동
3    1호선         신장림      장림동
4    1호선          장림      장림동
..   ...         ...      ...
109  4호선          석대      석대동
110  4호선   영산대(아랫반송)      반송동
111  4호선  동부산대학(윗반송)      반송동
112  4호선          고촌  철마면 고촌리
113  4호선  안평(고촌주택단지)  철마면 안평리

[114 rows x 3 columns]

In [134]:
df1.to_csv("부산지하철 역사별 행정동.csv", encoding="cp949", index=False)

In [135]:
pd.read_csv("./부산지하철 역사별 행정동.csv", encoding="cp949")

      선명          역명      행정동
0    1호선     다대포해수욕장      다대동
1    1호선        다대포항      다대동
2    1호선          낫개      다대동
3    1호선         신장림      장림동
4    1호선          장림      장림동
..   ...         ...      ...
109  4호선          석대      석대동
110  4호선   영산대(아랫반송)      반송동
111  4호선  동부산대학(윗반송)      반송동
112  4호선          고촌  철마면 고촌리
113  4호선  안평(고촌주택단지)  철마면 안평리

[114 rows x 3 columns]