# 부산광역시 동별 인구현황 전처리

# 코드 정의서
- a_pop : 행정동별 나이 인구수
- gu_gun(부산 행정구) : 강서구, 사상구, 사하구, 북구, 금정구, 동래구, 연제구, 부산진구, 서구, 동구, 남구, 중구, 영도구, 수영구, 해운대구, 기장군

In [1]:
import pandas as pd

In [31]:
# 데이터 불러오기
population_df = pd.read_csv("./data/부산광역시_읍면동별_연령_및_성별_202207.csv", encoding="cp949", index_col=False)
population_df

,연령별(1),연령별(2),강서구,강서구.1,강서구.2,대저1동,대저1동.1,대저1동.2,대저2동,대저2동.1,...,반송1동.2,반송2동,반송2동.1,반송2동.2,재송1동,재송1동.1,재송1동.2,재송2동,재송2동.1,재송2동.2
0,연령별(1),연령별(2),계 (명),남 (명),여 (명),계 (명),남 (명),여 (명),계 (명),남 (명),...,여 (명),계 (명),남 (명),여 (명),계 (명),남 (명),여 (명),계 (명),남 (명),여 (명)
1,총계,소계,144071,74610,69461,6417,3527,2890,7026,3959,...,6747,22756,11047,11709,37449,18368,19081,24138,11746,12392
2,0세∼4세,0세,1303,643,660,10,4,6,36,15,...,11,31,18,13,151,81,70,65,33,32
3,0세∼4세,1세,1323,742,581,12,2,10,36,26,...,7,43,26,17,170,87,83,68,33,35
4,0세∼4세,2세,1570,838,732,13,7,6,37,22,...,13,61,25,36,223,117,106,72,38,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,95세∼99세,95세,23,5,18,1,0,1,0,0,...,4,16,2,14,11,0,11,6,0,6
98,95세∼99세,96세,26,4,22,4,0,4,7,2,...,3,6,3,3,5,2,3,3,0,3
99,95세∼99세,97세,14,1,13,0,0,0,3,0,...,4,9,0,9,2,0,2,2,0,2
100,95세∼99세,98세,7,3,4,1,0,1,0,0,...,1,2,0,2,2,0,2,2,0,2
101,95세∼99세,99세,7,0,7,1,0,1,1,0,...,1,1,0,1,3,1,2,3,0,3

In [32]:
# 열 제거
population_df.drop(columns="연령별(1)", inplace=True)

In [33]:
# 행,열 변경
population_df = population_df.transpose()

In [34]:
population_df.rename(columns=population_df.iloc[0], inplace=True)

In [35]:
population_df.drop(population_df.index[0], inplace=True)

In [36]:
population_df.reset_index(inplace=True)

In [37]:
# 열 이름 변경
population_df.rename(columns={"연령별(2)":"성별", "소계":"합계","index":"행정구"}, inplace=True)

In [38]:
# 행정구역별 나이 인구수 Dataframe 생성
a_pop = population_df.drop(columns="성별")

In [39]:
# .을 문자로 인식하여 .1, .2포함 행 삭제
a_pop = a_pop[~a_pop['행정구'].str.contains("[.]")]

In [40]:
a_pop.reset_index(inplace=True)
a_pop.drop(columns="index",inplace=True)
a_pop

,행정구,합계,0세,1세,2세,3세,4세,5세,6세,7세,...,90세,91세,92세,93세,94세,95세,96세,97세,98세,99세
0,강서구,144071,1303,1323,1570,1758,1999,2183,2361,2383,...,126,81,83,69,45,23,26,14,7,7
1,대저1동,6417,10,12,13,18,19,17,15,19,...,22,13,14,8,6,1,4,0,1,1
2,대저2동,7026,36,36,37,32,55,45,54,45,...,11,12,7,8,6,0,7,3,0,1
3,강동동,4161,4,5,6,3,13,8,9,8,...,10,5,16,5,6,2,1,3,0,0
4,명지1동,53811,768,755,869,936,1027,1108,1116,1114,...,22,12,16,19,5,6,2,3,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,반여4동,15710,69,90,104,102,123,114,123,139,...,11,9,4,8,6,4,1,2,1,0
217,반송1동,13507,22,17,27,23,24,31,32,52,...,27,11,25,10,13,5,3,5,1,1
218,반송2동,22756,31,43,61,65,77,82,96,100,...,43,33,28,17,31,16,6,9,2,1
219,재송1동,37449,151,170,223,245,328,358,436,518,...,27,15,16,11,9,11,5,2,2,3
220,재송2동,24138,65,68,72,90,102,98,128,133,...,26,19,9,14,12,6,3,2,2,3

In [45]:
a_pop.to_csv("부산광역시 행정동.csv", index = False, encoding="cp949")
# 이후 엑셀로 수정

In [46]:
a_pop

,행정구,합계,0세,1세,2세,3세,4세,5세,6세,7세,...,90세,91세,92세,93세,94세,95세,96세,97세,98세,99세
0,강서구,144071,1303,1323,1570,1758,1999,2183,2361,2383,...,126,81,83,69,45,23,26,14,7,7
1,대저1동,6417,10,12,13,18,19,17,15,19,...,22,13,14,8,6,1,4,0,1,1
2,대저2동,7026,36,36,37,32,55,45,54,45,...,11,12,7,8,6,0,7,3,0,1
3,강동동,4161,4,5,6,3,13,8,9,8,...,10,5,16,5,6,2,1,3,0,0
4,명지1동,53811,768,755,869,936,1027,1108,1116,1114,...,22,12,16,19,5,6,2,3,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216,반여4동,15710,69,90,104,102,123,114,123,139,...,11,9,4,8,6,4,1,2,1,0
217,반송1동,13507,22,17,27,23,24,31,32,52,...,27,11,25,10,13,5,3,5,1,1
218,반송2동,22756,31,43,61,65,77,82,96,100,...,43,33,28,17,31,16,6,9,2,1
219,재송1동,37449,151,170,223,245,328,358,436,518,...,27,15,16,11,9,11,5,2,2,3
220,재송2동,24138,65,68,72,90,102,98,128,133,...,26,19,9,14,12,6,3,2,2,3

In [47]:
prop_a_pop = pd.read_csv("./부산광역시 행정동(전처리완).csv", encoding="cp949")

In [48]:
prop_a_pop

,구군별,읍면동별,합계,0세,1세,2세,3세,4세,5세,6세,...,90세,91세,92세,93세,94세,95세,96세,97세,98세,99세
0,강서구,대저1동,6417,10,12,13,18,19,17,15,...,22,13,14,8,6,1,4,0,1,1
1,강서구,대저2동,7026,36,36,37,32,55,45,54,...,11,12,7,8,6,0,7,3,0,1
2,강서구,강동동,4161,4,5,6,3,13,8,9,...,10,5,16,5,6,2,1,3,0,0
3,강서구,명지1동,53811,768,755,869,936,1027,1108,1116,...,22,12,16,19,5,6,2,3,1,4
4,강서구,명지2동,30337,196,211,280,376,443,527,629,...,13,10,6,10,5,3,5,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,해운대구,반여4동,15710,69,90,104,102,123,114,123,...,11,9,4,8,6,4,1,2,1,0
201,해운대구,반송1동,13507,22,17,27,23,24,31,32,...,27,11,25,10,13,5,3,5,1,1
202,해운대구,반송2동,22756,31,43,61,65,77,82,96,...,43,33,28,17,31,16,6,9,2,1
203,해운대구,재송1동,37449,151,170,223,245,328,358,436,...,27,15,16,11,9,11,5,2,2,3
204,해운대구,재송2동,24138,65,68,72,90,102,98,128,...,26,19,9,14,12,6,3,2,2,3